#服务端口
server: [8010]

#代理端口
proxy: [8020,8021,8022,8023,8024,8025,8026,8027,8028,8029]

#过滤链接
igonre: 
  - "www.google.es"
  - "accounts.google.com"
  - "www.gstatic.com"
  - "clients1.google.com"
  - "chrome-devtools-frontend.appspot.com"

#缓存
cache:

  #缓存目录
  dir: ".cache"

  #过期时间
  expire: "10000h"

  #缓存MIME
  types:
    - "text/css"
    - "image/png"
    - "image/gif"
    - "mage/gif"
    - "image/webp"
    - "image/jpeg"
    - "image/svg+xml"
    - "application/octet-stream"
    - "application/font-woff"
    - "application/javascript"
    - "application/x-javascript"
    - "text/javascript"
    - "font/woff"
    - "image/x-icon"

  #缓存URL
  urls:
    #ais
    - "http://ss1.mobilelife.co.th/js/jquery.min.js"
    - "http://ss1.mobilelife.co.th/js/bootstrap.min.js"
    - "http://ss1.mobilelife.co.th/js/utils.js"
    - "http://ss1.mobilelife.co.th/js/main.js"