server: [8010]
proxy: [8020]

igonre: ["www.google.es","accounts.google.com","www.gstatic.com","clients1.google.com"]

#缓存
cache:

  #缓存目录
  dir: ".cache"

  #过期时间
  expire: "12h"

  #缓存MIME
  types:
    - "text/css"
    - "image/png"
    - "image/gif"
    - "mage/gif"
    - "image/jpeg"
    - "application/octet-stream"
    - "application/font-woff"

  #缓存URL
  urls:
    #ais
    - "http://ss1.mobilelife.co.th/js/jquery.min.js"
    - "http://ss1.mobilelife.co.th/js/bootstrap.min.js"
    - "http://ss1.mobilelife.co.th/js/utils.js"
    - "http://ss1.mobilelife.co.th/js/main.js"